AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - Rakefile
    - bin/**/*

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

DotPosition:
  EnforcedStyle: leading

StringLiterals:
  EnforcedStyle: single_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ExtraSpacing:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
